apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: mi-aplicacion
  namespace: juan2space
spec:
  template:
    spec:
      containers:
        - image: nginx:latest  # Imagen de NGINX desde Docker Hub
          env:
            - name: MY_ENV_VAR
              value: "value"
